### PR TITLE
SCRUM-15: Swagger

### PR DESCRIPTION
**Pull request by nyotie-tao**
image

### CODE REVIEW

**Comment by Hannibal0416** [comment]
Based on your design, do we also need to add the POST "type" and "brand" these two endpoints in the metadata?

**Comment by nyotie-tao** [comment]
> Based on your design, do we also need to add the POST "type" and "brand" these two endpoints in the metadata?

IMO no need to waste time implementing those endpoints. Better use the time to implement other feature.
After all our goal is not to complete this project but to test webflux and reactive

**Comment by Hannibal0416** [comment]
could you also export the swagger into a yaml file? and then put it under the doc/swagger?
you can find the JSON in http://localhost:8082/v3/api-docs
and then use https://editor.swagger.io/ to convert it into a yaml file.
Thanks!

**Comment by nyotie-tao** [comment]
@Hannibal0416 added

**Review by Hannibal0416 — APPROVED** [review]
Looks good!

**Pull request merged**
